# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_guide', '0002_contact_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('order_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('pars', models.PositiveSmallIntegerField()),
                ('unit', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Purveryor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=12)),
            ],
        ),
    ]
