# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-03 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_guide', '0004_order_ordernumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='purveryor',
            name='name',
            field=models.CharField(choices=[(b'IFS', b'IFS'), (b'SYSCO', b'Sysco'), (b'PRODUCE', b"Nature's Produce"), (b'MEAT', b'Rocker Bros')], default='Sysco', max_length=100),
            preserve_default=False,
        ),
    ]
