# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-03 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_guide', '0006_auto_20180303_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='unit',
            field=models.CharField(choices=[(b'#', b'lbs'), (b'cases', b'cases'), (b'bunches', b'bunches'), (b'each', b'each'), (b'tub', b'tub'), (b'bag', b'bag'), (b'quarts', b'quarts'), (b'gallon', b'gallon'), (b'bottle', b'bottle')], max_length=20),
        ),
    ]
