# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-04 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_guide', '0007_auto_20180303_1406'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purveryor',
            new_name='Purveyor',
        ),
    ]
