# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_guide', '0008_auto_20180304_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.CharField(choices=[(b'Tuesday 03/06/2018', b'Tuesday 03/06/2018'), (b'Wednesday 03/07/2018', b'Wednesday 03/07/2018'), (b'Thursday 03/08/2018', b'Thursday 03/08/2018'), (b'Friday 03/09/2018', b'Friday 03/09/2018'), (b'Saturday 03/10/2018', b'Saturday 03/10/2018'), (b'Sunday 03/11/2018', b'Sunday 03/11/2018'), (b'Monday 03/12/2018', b'Monday 03/12/2018')], default=b'Monday 03/05/2018', max_length=100),
            preserve_default=False,
        ),
    ]
