# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_guide', '0009_order_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordernumber',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='complete_order',
            field=models.TextField(default='1 x Item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.CharField(choices=[(b'Friday 03/09/2018', b'Friday 03/09/2018'), (b'Saturday 03/10/2018', b'Saturday 03/10/2018'), (b'Sunday 03/11/2018', b'Sunday 03/11/2018'), (b'Monday 03/12/2018', b'Monday 03/12/2018'), (b'Tuesday 03/13/2018', b'Tuesday 03/13/2018'), (b'Wednesday 03/14/2018', b'Wednesday 03/14/2018'), (b'Thursday 03/15/2018', b'Thursday 03/15/2018')], max_length=100),
        ),
    ]
