# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-11 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_guide', '0010_auto_20180308_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.CharField(choices=[(b'Monday 03/12/2018', b'Monday 03/12/2018'), (b'Tuesday 03/13/2018', b'Tuesday 03/13/2018'), (b'Wednesday 03/14/2018', b'Wednesday 03/14/2018'), (b'Thursday 03/15/2018', b'Thursday 03/15/2018'), (b'Friday 03/16/2018', b'Friday 03/16/2018'), (b'Saturday 03/17/2018', b'Saturday 03/17/2018'), (b'Sunday 03/18/2018', b'Sunday 03/18/2018')], max_length=100),
        ),
    ]
