# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-11 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_guide', '0012_ordereditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete_order',
        ),
    ]
