# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-25 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_guide', '0013_remove_order_complete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.CharField(choices=[(b'Monday 03/26/2018', b'Monday 03/26/2018'), (b'Tuesday 03/27/2018', b'Tuesday 03/27/2018'), (b'Wednesday 03/28/2018', b'Wednesday 03/28/2018'), (b'Thursday 03/29/2018', b'Thursday 03/29/2018'), (b'Friday 03/30/2018', b'Friday 03/30/2018'), (b'Saturday 03/31/2018', b'Saturday 03/31/2018'), (b'Sunday 04/01/2018', b'Sunday 04/01/2018')], max_length=100),
        ),
    ]
